from typing import Any, Protocol

class MCPToolProvider(Protocol):
    """Boundary for the future MCP client/server implementation."""
    def describe_object(self, object_name: str) -> dict[str, Any]: ...
    def search_metadata(self, search_text: str) -> list[dict[str, Any]]: ...
    def execute_soql(self, soql: str) -> list[dict[str, Any]]: ...
    def get_data_lineage(self, request_id: str) -> dict[str, Any]: ...
    def get_audit_trail(self, audit_id: str) -> dict[str, Any]: ...

# Register these read-only operations with the chosen MCP framework.
